public enum Genre {
    ACTION, ADVENTURE, COMEDY, DRAMA, HORROR, SF, FANTASY, ROMANCE, MYSTERY, THRILLER, CRIME, BIOGRAPHY, WAR,
    WESTERN, MUSICAL, FAMILY, HISTORY, SPORTS, ANIMATION, MINISERIES, DOCUMENTARY, MOCKUMENTARY, ROM_COM, SUPERHERO
}
