
public enum Genre {
    ACTION, ADVENTURE, COMEDY, DRAMA, HORROR, SF, FANTASY, ROMANCE, MYSTERY, THRILLER, CRIME, BIOGRAPHY, WAR,
    WESTERN, MUSICAL, FAMILY, HISTORY, SPORTS, ANIMATION, MINISERIES, DOCUMENTARY, MOCKUMENTARY, ROM_COM, SUPERHERO,
    COOKING, TALK_SHOW, REALITY_SHOW, NEWS, GAME_SHOW, TRAVEL, HOME_AND_GARDEN, TUTORIAL, EDUCATION, RELIGION
}
